apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: test-jul11-allsamens
  janus-idp.io/tekton: test-jul11-allsamens
  backstage.io/kubernetes-id: test-jul11-allsamens
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: test-jul11-allsamens
resources:
  - application-dev.yaml