apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: test-jul11-allsamens
  janus-idp.io/tekton: test-jul11-allsamens
  backstage.io/kubernetes-id: test-jul11-allsamens
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: test-jul11-allsamens
resources:
  - initialize-namespace/
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
