apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: test-jul11-allsamens
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-jul11-allsamens
  name: test-jul11-allsamens
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-jul11-allsamens
    weight: 100
  wildcardPolicy: None
