apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: test-jul11-allsamens
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-jul11-allsamens
  name: test-jul11-allsamens
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: test-jul11-allsamens
